config/routes.rb
Rails.application.routes.draw do
  resources :fiscal_years
  resources :transactions
  resources :clients
  namespace :admin do
    resources :users
    resources :clients
    resources :fiscal_years
    resources :transactions
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
	has_many :transactions
	belongs_to :client
	
end

app/controllers/admin/fiscal_years_controller.rb
module Admin
  class FiscalYearsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = FiscalYear.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   FiscalYear.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/fiscal_years_controller.rb
class FiscalYearsController < ApplicationController
  before_action :set_fiscal_year, only: [:show, :edit, :update, :destroy]

  # GET /fiscal_years
  # GET /fiscal_years.json
  def index
    @fiscal_years = FiscalYear.all
  end

  # GET /fiscal_years/1
  # GET /fiscal_years/1.json
  def show
  end

  # GET /fiscal_years/new
  def new
    @fiscal_year = FiscalYear.new
  end

  # GET /fiscal_years/1/edit
  def edit
  end

  # POST /fiscal_years
  # POST /fiscal_years.json
  def create
    @fiscal_year = FiscalYear.new(fiscal_year_params)

    respond_to do |format|
      if @fiscal_year.save
        format.html { redirect_to @fiscal_year, notice: 'Fiscal year was successfully created.' }
        format.json { render :show, status: :created, location: @fiscal_year }
      else
        format.html { render :new }
        format.json { render json: @fiscal_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiscal_years/1
  # PATCH/PUT /fiscal_years/1.json
  def update
    respond_to do |format|
      if @fiscal_year.update(fiscal_year_params)
        format.html { redirect_to @fiscal_year, notice: 'Fiscal year was successfully updated.' }
        format.json { render :show, status: :ok, location: @fiscal_year }
      else
        format.html { render :edit }
        format.json { render json: @fiscal_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiscal_years/1
  # DELETE /fiscal_years/1.json
  def destroy
    @fiscal_year.destroy
    respond_to do |format|
      format.html { redirect_to fiscal_years_url, notice: 'Fiscal year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiscal_year
      @fiscal_year = FiscalYear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fiscal_year_params
      params.require(:fiscal_year).permit(:client_id, :year, :transactions)
    end
end

app/helpers/fiscal_years_helper.rb
module FiscalYearsHelper
end

app/views/fiscal_years/_form.html.erb
<%= form_for(fiscal_year) do |f| %>
  <% if fiscal_year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fiscal_year.errors.count, "error") %> prohibited this fiscal_year from being saved:</h2>

      <ul>
      <% fiscal_year.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %>
    <%= f.number_field :client_id %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :transactions %>
    <%= f.text_field :transactions %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiscal_years/edit.html.erb
<h1>Editing Fiscal Year</h1>

<%= render 'form', fiscal_year: @fiscal_year %>

<%= link_to 'Show', @fiscal_year %> |
<%= link_to 'Back', fiscal_years_path %>

app/views/fiscal_years/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fiscal Years</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Year</th>
      <th>Transactions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fiscal_years.each do |fiscal_year| %>
      <tr>
        <td><%= fiscal_year.client_id %></td>
        <td><%= fiscal_year.year %></td>
        <td><%= fiscal_year.transactions %></td>
        <td><%= link_to 'Show', fiscal_year %></td>
        <td><%= link_to 'Edit', edit_fiscal_year_path(fiscal_year) %></td>
        <td><%= link_to 'Destroy', fiscal_year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fiscal Year', new_fiscal_year_path %>

app/views/fiscal_years/new.html.erb
<h1>New Fiscal Year</h1>

<%= render 'form', fiscal_year: @fiscal_year %>

<%= link_to 'Back', fiscal_years_path %>

app/views/fiscal_years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @fiscal_year.client_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @fiscal_year.year %>
</p>

<p>
  <strong>Transactions:</strong>
  <%= @fiscal_year.transactions %>
</p>

<%= link_to 'Edit', edit_fiscal_year_path(@fiscal_year) %> |
<%= link_to 'Back', fiscal_years_path %>